#
# Makefile for the sysfs virtual filesystem
#

O_TARGET := sysfs.o

export-objs	:= inode.o file.o dir.o symlink.o mount.o bin.o

obj-y           := inode.o file.o dir.o symlink.o mount.o bin.o

include $(TOPDIR)/Rules.make
